/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2016-02-22 15:24:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class maintenance_002demp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html ng-app>\r\n");
      out.write("  <head>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./css/materialize.min.css\"  media=\"screen,projection\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/materialize.css\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/mystyle.css\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/mtnc-emp.css\"/>\r\n");
      out.write("    <!--Let browser know website is optimized for mobile-->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body class=\"blue-grey lighten-5\">\r\n");
      out.write("  <div class=\"wrapper\">\r\n");
      out.write("            <header class=\"headnav\">\r\n");
      out.write("                <ul id=\"slide-out\" class=\"side-nav fixed z-depth-0\">\r\n");
      out.write("                  <div class=\"center\">\r\n");
      out.write("                      <img src=\"./img/anon.jpg\" class=\"circle\" style=\"width: 150px; height: 150px; margin-top: 40px; margin-bottom: 20px;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  <li><a href=\"admin-home.jsp\" class=\"waves-effect waves-orange\"><b>Home</b></a></li>\r\n");
      out.write("                 <!--  <li class=\"no-padding\"> -->\r\n");
      out.write("                    <ul class=\"collapsible\" data-collapsible=\"accordion\">\r\n");
      out.write("                      <li>\r\n");
      out.write("                        <a class=\"collapsible-header\"><b>Maintenance</b></a>\r\n");
      out.write("                          <div class=\"collapsible-body\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                              <li class=\"orange\"><a href=\"maintenance-emp.jsp\">Employee</a></li>\r\n");
      out.write("                              <li><a href=\"maintenance-prodsvc.jsp\">Product & Service</a></li>\r\n");
      out.write("                              <li><a href=\"maintenance-promdisc.jsp\">Promo</a></li>\r\n");
      out.write("                              <li><a href=\"maintenance-package.jsp\">Discount</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li>\r\n");
      out.write("                        <a class=\"collapsible-header\"><b>Transaction</b></a>\r\n");
      out.write("                          <div class=\"collapsible-body\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                              <li><a href=\"transactions-reservation.jsp\">Reservation</a></li>\r\n");
      out.write("                              <li><a href=\"transactions-productorder.jsp\">Product Order</a></li>\r\n");
      out.write("                              <li><a href=\"#!\">Walk-In</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  <li><a href=\"utilities.jsp\" class=\"waves-effect waves-orange\"><b>Utilities</b></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("               <nav class=\"z-depth-0\">\r\n");
      out.write("                 <div class=\"nav-wrapper orange\">\r\n");
      out.write("                   <a href=\"#!\" class=\"brand-logo white-text\" style=\"margin-left: 30px;\">Salon Management System</a>\r\n");
      out.write("                 \r\n");
      out.write("                   <a href=\"#\" data-activates=\"mobile-demo\" class=\"button-collapse\"><i class=\"material-icons\">menu</i></a>\r\n");
      out.write("                   <ul class=\"side-nav\" id=\"mobile-demo\">\r\n");
      out.write("                     <li><a href=\"admin-home.jsp\" class=\"waves-effect waves-orange\"><b>Home</b></a>\r\n");
      out.write("                       <ul class=\"collapsible collapsible-accordion\">\r\n");
      out.write("                         <li>\r\n");
      out.write("                           <a class=\"waves-effect waves-orange collapsible-header\"><b>Maintenance</b></a>\r\n");
      out.write("                             <div class=\"collapsible-body\">\r\n");
      out.write("                               <ul>\r\n");
      out.write("                                 <li class=\"orange\"><a href=\"maintenance-emp.jsp\">Employee</a></li>\r\n");
      out.write("                                 <li><a href=\"maintenance-prodsvc.jsp\">Product & Service</a></li>\r\n");
      out.write("                                 <li><a href=\"maintenance-promdisc.jsp\">Promo</a></li>\r\n");
      out.write("                                 <li><a href=\"maintenance-package.jsp\">Discount</a></li>\r\n");
      out.write("                               </ul>\r\n");
      out.write("                             </div>\r\n");
      out.write("                         </li>\r\n");
      out.write("                         <li>\r\n");
      out.write("                           <a class=\"waves-effect waves-orange collapsible-header\"><b>Transaction</b></a>\r\n");
      out.write("                             <div class=\"collapsible-body\">\r\n");
      out.write("                               <ul>\r\n");
      out.write("                                 <li><a href=\"transactions-reservation.jsp\">Reservation</a></li>\r\n");
      out.write("                                 <li><a href=\"transactions-productorder.jsp\">Product Order</a></li>\r\n");
      out.write("                                 <li><a href=\"#!\">Walk-In</a></li>\r\n");
      out.write("                               </ul>\r\n");
      out.write("                             </div>\r\n");
      out.write("                         </li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                    <li><a href=\"utilities.jsp\" class=\"waves-effect waves-orange\"><b>Utilities</b></a></li>\r\n");
      out.write("                   </ul>\r\n");
      out.write("                 </div>\r\n");
      out.write("               </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <article>\r\n");
      out.write("          <div class=\"wrapper\">\r\n");
      out.write("                    <div class=\"aside aside1 z-depth-barts\">\r\n");
      out.write("                      <header><h4>Create Employee</h4><div class=\"divider\"></div></header>\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"row\">\r\n");
      out.write("                          <form class=\"col s12\" action=\"createEmployee\" onsubmit=\"return passvalidation()\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("                                  <div class=\"input-field col s4\">\r\n");
      out.write("                                      <label class=\"red-text\">(*) Indicates required field</label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s6 offset-s2\">\r\n");
      out.write("                                      <img  id=\"employeeimg\" style=\"width: 120px; height: 120px;\" src=\"./img/anon.jpg\" alt=\"\"/>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s4\">\r\n");
      out.write("                                      <input id=\"empid\" type=\"text\" disabled=\"disabled\">\r\n");
      out.write("                                      <label for=\"empid\">Employee ID</label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s7 offset-s1\">\r\n");
      out.write("                                      <div class=\"file-field\">\r\n");
      out.write("                                            <div class=\"btn orange\">\r\n");
      out.write("                                              <span class=\"\">Image</span>\r\n");
      out.write("                                              <input name=\"upload\" type=\"file\" accept=\"image/jpeg,image/png\" onchange=\"loadFile(event)\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"file-path-wrapper\">\r\n");
      out.write("                                              <input name=\"path\" class=\"file-path validate\" type=\"text\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s4\">\r\n");
      out.write("                                      <input name=\"strEmpFirstName\" id=\"fname\" type=\"text\" class=\"validate active\" required>\r\n");
      out.write("                                      <label for=\"fname\">First Name<span class=\"red-text\">*</span></label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s4\">\r\n");
      out.write("                                      <input name=\"strEmpMiddleName\" id=\"mname\" type=\"text\" class=\"validate\">\r\n");
      out.write("                                      <label for=\"mname\">Middle Name</label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s4\">\r\n");
      out.write("                                      <input name=\"strEmpLastName\" id=\"lname\" type=\"text\" class=\"validate\" required>\r\n");
      out.write("                                      <label for=\"lname\">Last Name<span class=\"red-text\">*</span></label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                      <div class=\"input-field col s3\">\r\n");
      out.write("                                          <select id=\"month\" name=\"strMonth\">\r\n");
      out.write("                                              <option value=\"1\">January</option>\r\n");
      out.write("                                              <option value=\"2\">February</option>\r\n");
      out.write("                                              <option value=\"3\">March</option>\r\n");
      out.write("                                              <option value=\"4\">April</option>\r\n");
      out.write("                                              <option value=\"5\">May</option>\r\n");
      out.write("                                              <option value=\"6\">June</option>\r\n");
      out.write("                                              <option value=\"7\">July</option>\r\n");
      out.write("                                              <option value=\"8\">August</option>\r\n");
      out.write("                                              <option value=\"9\">September</option>\r\n");
      out.write("                                              <option value=\"10\">October</option>\r\n");
      out.write("                                              <option value=\"11\">November</option>\r\n");
      out.write("                                              <option value=\"12\">December</option>\r\n");
      out.write("                                          </select>\r\n");
      out.write("                                          <label>Month <span class=\"red-text\">*</span></label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"input-field col s2\">\r\n");
      out.write("                                          <input name=\"strDay\" type=\"text\" class=\"validate\" id=\"day\" maxlength=\"2\">\r\n");
      out.write("                                          <label for=\"day\">Day <span class=\"red-text\">*</span></label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"input-field col s3\">\r\n");
      out.write("                                          <input name=\"strYear\" type=\"text\" class=\"validate\" id=\"year\" maxlength=\"4\">\r\n");
      out.write("                                          <label for=\"year\">Year <span class=\"red-text\">*</span></label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                      <div class=\"input-field col s4\">\r\n");
      out.write("                                          <input type=\"text\" class=\"validate\" disabled value=\"\">\r\n");
      out.write("                                          <label style=\"color: #9e9e9e;\">Age: <span id=\"age\"></span></label>\r\n");
      out.write("                                          \r\n");
      out.write("                                      </div>\r\n");
      out.write("                                  <div class=\"input-field col s6\" >\r\n");
      out.write("                                      <select name=\"strEmpGender\" required>\r\n");
      out.write("                                        <option value=\"\" disabled selected></option>\r\n");
      out.write("                                        <option value=\"M\">Male</option>\r\n");
      out.write("                                        <option value=\"F\">Female</option>\r\n");
      out.write("                                      </select>\r\n");
      out.write("                                      <label>Gender <span class=\"red-text\">*</span></label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s1\">\r\n");
      out.write("                                    <p style=\"margin-top: 12px; margin-left: -7px;\">(+63)</p>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s5\">\r\n");
      out.write("                                      <input name=\"strEmpContactNo\" type=\"text\" id=\"contact\" class=\"validate\" maxlength=\"10\">\r\n");
      out.write("                                      <label for=\"contact\">Contact Number</label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s12\">\r\n");
      out.write("                                      <input name=\"strEmpAddress\" type=\"text\" id=\"address\" class=\"validate\">\r\n");
      out.write("                                      <label for=\"address\">Address <span class=\"red-text\">*</span></label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s12\">\r\n");
      out.write("                                      <p style=\"color:#9e9e9e;font-size:12px;\">Position <span class=\"red-text\">*</span></p>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s5\" style=\"margin-top: -1px;\">\r\n");
      out.write("                                      <select id=\"slct1\" name=\"selectedJob\" multiple=\"multiple\">\r\n");
      out.write("                                          <option value=\"\" disabled selected> </option>\r\n");
      out.write("                                          ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                      </select>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s2\" style=\"margin-top: -0.2px;\">\r\n");
      out.write("                                      <p style=\"margin-top: 5px;\" class=\"center\"><a id=\"optionadd\" class=\"waves-effect waves-light orange-btn\"><i class=\"material-icons small\">add</i></a><a class=\"waves-effect waves-light orange-btn\" onclick=\"removeopt()\"><i class=\"material-icons small\">remove</i></a></p>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s4\" style=\"margin-top: -4px;\">\r\n");
      out.write("                                      <input type=\"text\" id=\"add-optname\" class=\"validate\">\r\n");
      out.write("                                      <label for=\"add-optname\">Another position</label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"divider col s12\" style=\"margin-top: 20px;\"></div>\r\n");
      out.write("                                  <div class=\"col s12\"  style=\"margin-top: 10px;\">\r\n");
      out.write("                                      <h4>Account</h4>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s6 offset-s3\">\r\n");
      out.write("                                      <input name=\"strEmpUsername\" type=\"text\" class=\"validate\" id=\"user\" maxlength=\"15\">\r\n");
      out.write("                                      <label for=\"user\">Username</label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s6 offset-s3\">\r\n");
      out.write("                                      <input name=\"strEmpPassword\" type=\"password\" class=\"validate\" id=\"pass\" maxlength=\"20\" onkeyup=\"checkPass(); return false;\">\r\n");
      out.write("                                      <label for=\"pass\">Password <span id=\"pw1\"></span></label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s6 offset-s3\">\r\n");
      out.write("                                      <input name=\"strEmpPassword2\" type=\"password\" class=\"validate\" id=\"conf-pass\" maxlength=\"20\" onkeyup=\"checkPass(); return false;\">\r\n");
      out.write("                                      <label for=\"conf-pass\">Confirm Password <span id=\"pw2\"></span></label>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"input-field col s6 offset-s3\">\r\n");
      out.write("                                      <span id=\"confirmMsg\" class=\"confirmMsg\"></span>\r\n");
      out.write("                                  </div>\r\n");
      out.write("\r\n");
      out.write("                                  <div class=\"input-field col s12\"> \r\n");
      out.write("                                      <button class=\"waves-effect waves-white btn-flat orange\" title=\"Create\" type=\"submit\" value=\"Submit\" id=\"savebtn\" disabled=\"disabled\" onclick=\"success()\">Create</button>\r\n");
      out.write("                                      <button class=\"waves-effect waves-orange btn-flat white\" type=\"reset\" value=\"Reset\" title=\"Clear\">CLEAR</button>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("\r\n");
      out.write("                              <!-- ADD OPTION POSITION -->\r\n");
      out.write("                                \r\n");
      out.write("\r\n");
      out.write("                          </form>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"aside aside2 z-depth-barts\">\r\n");
      out.write("                                    <nav class=\"z-depth-0\">\r\n");
      out.write("                                      <div class=\"nav-wrapper grey lighten-3 grey-text text-darken-4\">\r\n");
      out.write("                                        <form>\r\n");
      out.write("                                          <div class=\"input-field col s12 z-depth-0\">\r\n");
      out.write("                                            <input class=\"grey lighten-1\" id=\"search\" type=\"search\" ng-model=\"name\">\r\n");
      out.write("                                            <label for=\"search\"><i class=\"material-icons grey-text text-darken-3\">search</i></label>\r\n");
      out.write("                                          </div>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                    </nav>\r\n");
      out.write("                     <div class=\"row\">\r\n");
      out.write("                         <div class=\"col s12\">\r\n");
      out.write("                             <div class=\"row\">\r\n");
      out.write("                                    <h5>Employee List</h5>\r\n");
      out.write("                                    <ul class=\"collapsible z-depth-0\" data-collapsible=\"accordion\" ng-init=\"emp=[{name:'Han Ainan',lastname:'Ongsip'},{name:'John Angelo',lastname:'Barot'},{name:'Joshua',lastname:'Mercado'}]\">\r\n");
      out.write("                                        <li ng-repeat=\"employee in emp | filter: name | orderBy: 'lastname'\">\r\n");
      out.write("                                          <div class=\"collapsible-header\">\r\n");
      out.write("                                              {{employee.name}} {{employee.lastname}}\r\n");
      out.write("                                          </div>\r\n");
      out.write("                                          <div class=\"collapsible-body blue-grey lighten-5\"><a href=\"#modaledit\" class=\"modal-trigger waves-effect waves-orange btn-flat\">Update</a>\r\n");
      out.write("                                          <a  class=\"waves-effect waves-orange btn-flat red-text\">Deactivate</a></div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <!-- <li>\r\n");
      out.write("                                          <div class=\"collapsible-header\">\r\n");
      out.write("                                              <img src=\"./img/barts.jpg\" style=\"width: 30px;height: 30px; margin-top: 6px;\" class=\"circle left\"/>\r\n");
      out.write("                                              John Angelo C. Barot\r\n");
      out.write("                                          </div>\r\n");
      out.write("                                          <div class=\"collapsible-body blue-grey lighten-5\">\r\n");
      out.write("                                          <a class=\"waves-effect waves-orange btn-flat\">Edit</a>\r\n");
      out.write("                                          <a class=\"waves-effect waves-orange btn-flat red-text\">Delete</a></div>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                          <div class=\"collapsible-header\">\r\n");
      out.write("                                              <img src=\"./img/joshua.jpg\" style=\"width: 30px;height: 30px; margin-top: 6px;\" class=\"circle left\"/>\r\n");
      out.write("                                              Joshua N. Mercado\r\n");
      out.write("                                          </div> -->\r\n");
      out.write("                                      </ul>\r\n");
      out.write("\r\n");
      out.write("                                      <div id=\"modaledit\" class=\"modal modal-fixed-footer\">\r\n");
      out.write("                                          <div class=\"modal-content\">\r\n");
      out.write("                                            <h4>Update Employee</h4>\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                              <form class=\"col s12\" action=\"\">\r\n");
      out.write("                                                  <div class=\"row\">\r\n");
      out.write("                                                      <div class=\"input-field col s5 offset-s7\">\r\n");
      out.write("                                                          <img  id=\"output2\" style=\"width: 120px; height: 120px;\" src=\"./img/ainan.jpg\" alt=\"\"/>\r\n");
      out.write("                                                      </div>\r\n");
      out.write("                                                      <div class=\"input-field col s4\">\r\n");
      out.write("                                                          <input type=\"text\" id=\"en\" validate disabled=\"disabled\">\r\n");
      out.write("                                                          <label for=\"en\">Employee Number</label>\r\n");
      out.write("                                                      </div>\r\n");
      out.write("                                                      <div class=\"input-field col s5 offset-s3\">\r\n");
      out.write("                                                          <div class=\"file-field\">\r\n");
      out.write("                                                                <div class=\"btn orange\">\r\n");
      out.write("                                                                  <span class=\"\">Image</span>\r\n");
      out.write("                                                                  <input type=\"file\" accept=\"image/*\" onchange=\"editFile(event)\">\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"file-path-wrapper\">\r\n");
      out.write("                                                                  <input class=\"file-path validate\" type=\"text\">\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                      </div>\r\n");
      out.write("                                                      <div class=\"input-field col s12\">\r\n");
      out.write("                                                          <input type=\"text\" id=\"fn\" validate disabled=\"disabled\">\r\n");
      out.write("                                                          <label for=\"fn\">First Name</label>\r\n");
      out.write("                                                      </div>\r\n");
      out.write("                                                  </div>\r\n");
      out.write("                                              </form>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                          </div>\r\n");
      out.write("                                          <div class=\"modal-footer\">\r\n");
      out.write("                                            <a href=\"#!\" class=\"modal-action modal-close waves-effect waves-orange btn-flat\">Cancel</a>\r\n");
      out.write("                                            <button type=\"submit\" value=\"Submit\" class=\"modal-action waves-effect waves-light orange btn-flat \">Confirm</button>\r\n");
      out.write("                                          </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </article>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!--Import jQuery before materialize.js-->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/materialize.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/angular.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("      $( document ).ready(function(){\r\n");
      out.write("        $(\".button-collapse\").sideNav();\r\n");
      out.write("          // Initialize collapsible (uncomment the line below if you use the dropdown variation)\r\n");
      out.write("        $('.collapsible').collapsible();\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("    <!-- bday -->\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        $('.datepicker').pickadate({\r\n");
      out.write("          selectMonths: true, // Creates a dropdown to control month\r\n");
      out.write("          selectYears: 15 // Creates a dropdown of 15 years to control year\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Upload image -->\r\n");
      out.write("\r\n");
      out.write("    <script text=\"text/javascript\">\r\n");
      out.write("      var loadFile = function(event) {\r\n");
      out.write("        var employeeimg = document.getElementById('employeeimg');\r\n");
      out.write("        employeeimg.src = URL.createObjectURL(event.target.files[0]);\r\n");
      out.write("      };\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script text=\"text/javascript\">\r\n");
      out.write("      var loadFile = editFile(event) {\r\n");
      out.write("        var output2 = document.getElementById('output2');\r\n");
      out.write("        output2.src = URL.createObjectURL(event.target.files[0]);\r\n");
      out.write("      };\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("      $(document).ready(function() {\r\n");
      out.write("          $('select').material_select();\r\n");
      out.write("        });\r\n");
      out.write("      </script>\r\n");
      out.write("\r\n");
      out.write("    <!--- Modal -->\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("            // the \"href\" attribute of .modal-trigger must specify the modal ID that wants to be triggered\r\n");
      out.write("            $('.modal-trigger').leanModal();\r\n");
      out.write("          }); \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("          function checkPass(){\r\n");
      out.write("            var pass1 = document.getElementById('password').value;\r\n");
      out.write("            var pass2 = document.getElementById('conf-password').value;\r\n");
      out.write("            var good = \"#66cc66\";\r\n");
      out.write("            var bad = \"#ff6666\";\r\n");
      out.write("\r\n");
      out.write("            if(pass1 == pass2 && pass2 == pass1 && pass1 != null && pass2 != null) {\r\n");
      out.write("              document.getElementById('confirmMsg').style.color = good;\r\n");
      out.write("              document.getElementById('confirmMsg').innerHTML = \"Password Match!\";\r\n");
      out.write("              document.getElementById('savebtn').disabled = false;\r\n");
      out.write("            }else{\r\n");
      out.write("              document.getElementById('confirmMsg').style.color = bad;\r\n");
      out.write("              document.getElementById('confirmMsg').style.color = bad;\r\n");
      out.write("              document.getElementById('confirmMsg').innerHTML = \"Password Do Not Match!\";\r\n");
      out.write("              document.getElementById('savebtn').disabled = true;\r\n");
      out.write("            }\r\n");
      out.write("          }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <!-- add option -->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("           $(document).ready(function(){\r\n");
      out.write("              $(\"#optionadd\").click(function(){\r\n");
      out.write("                 var addopt = $(\"#add-optname\").val();\r\n");
      out.write("                 if(jQuery.trim(addopt).length > 0){\r\n");
      out.write("                      var o = new Option(addopt, addopt, true);\r\n");
      out.write("                      /// jquerify the DOM object 'o' so we can use the html method\r\n");
      out.write("                      $(o).html(addopt);\r\n");
      out.write("                      $(\"#slct1\").append(o);\r\n");
      out.write("                 }else{\r\n");
      out.write("                  $(\"<div title='Error!'>Empty</div>\").dialog();\r\n");
      out.write("                 }\r\n");
      out.write("                   \r\n");
      out.write("                   });\r\n");
      out.write("                  \r\n");
      out.write("                });\r\n");
      out.write("    </script>\r\n");
      out.write("   \r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("      function removeopt(){\r\n");
      out.write("        var x = document.getElementById(\"slct1\");\r\n");
      out.write("        var y = document.getElementById(\"slct2\");\r\n");
      out.write("\r\n");
      out.write("        x.remove(x.selectedIndex);\r\n");
      out.write("        y.remove(y.selectedIndex);\r\n");
      out.write("      }\r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("   var month = document.getElementById('month').value;\r\n");
      out.write("   var day = document.getElementById('day').value;\r\n");
      out.write("   var year = document.getElementById('year').value;\r\n");
      out.write("\r\n");
      out.write("   var curday = new Date();\r\n");
      out.write("   var mm = curday.getMonth()+1;\r\n");
      out.write("   var dd = curday.getDate();\r\n");
      out.write("   var yyyy = curday.getFullYear();\r\n");
      out.write("\r\n");
      out.write("   var bday = month+'/'+day+'/'+year;\r\n");
      out.write("   var today = mm+'/'+dd+'/'+yyyy;\r\n");
      out.write("   \r\n");
      out.write("   if(day<32 && month!='' || day!='' || year!=''){\r\n");
      out.write("         if(month<=mm && day<=dd && year<=yyyy && day!='' && year>0){\r\n");
      out.write("               var myage = yyyy - year;\r\n");
      out.write("               document.getElementById('age').innerHTML = myage;\r\n");
      out.write("               document.getElementById('age').style.color = \"black\";\r\n");
      out.write("         } else if(month>=mm && day>dd && year<yyyy && year>0){\r\n");
      out.write("           var myage = yyyy-year;\r\n");
      out.write("           document.getElementById('age').innerHTML = myage-1;\r\n");
      out.write("           document.getElementById('age').style.color = \"black\";\r\n");
      out.write("         } else if(month>=mm && day<dd && year<yyyy && year>0){\r\n");
      out.write("           var myage = yyyy-year;\r\n");
      out.write("           document.getElementById('age').innerHTML = myage-1;\r\n");
      out.write("           document.getElementById('age').style.color = \"black\";\r\n");
      out.write("         }else if(year=='' || day=='' || month==''){\r\n");
      out.write("           document.getElementById('age').innerHTML = \" \";\r\n");
      out.write("         }else if(year>yyyy){\r\n");
      out.write("           document.getElementById('age').innerHTML = \"dpa buhay\";\r\n");
      out.write("           document.getElementById('age').style.color = \"red\";\r\n");
      out.write("         }\r\n");
      out.write("     }\r\n");
      out.write("    else{\r\n");
      out.write("         document.getElementById('age').innerHTML = \"\";\r\n");
      out.write("    }\r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("         function checkPass(){\r\n");
      out.write("           var pass1 = document.getElementById('pass').value;\r\n");
      out.write("           var pass2 = document.getElementById('conf-pass').value;\r\n");
      out.write("           var good = \"#66cc66\";\r\n");
      out.write("           var bad = \"#ff6666\";\r\n");
      out.write("\r\n");
      out.write("           if(pass1 == pass2 && pass2 == pass1 && pass1 != \"\" && pass2 != \"\") {\r\n");
      out.write("             document.getElementById('confirmMsg').style.color = good;\r\n");
      out.write("             document.getElementById('confirmMsg').innerHTML = \"Password Match!\";\r\n");
      out.write("             document.getElementById('savebtn').disabled = false;\r\n");
      out.write("           }else{\r\n");
      out.write("             document.getElementById('confirmMsg').style.color = bad;\r\n");
      out.write("             document.getElementById('confirmMsg').style.color = bad;\r\n");
      out.write("             document.getElementById('confirmMsg').innerHTML = \"Password Do Not Match!\";\r\n");
      out.write("             document.getElementById('savebtn').disabled = true;\r\n");
      out.write("           }\r\n");
      out.write("         }\r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("      function success(){\r\n");
      out.write("        alert(\"Successfully Created\");\r\n");
      out.write("      }\r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /maintenance-emp.jsp(183,42) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/maintenance-emp.jsp(183,42) '${empCategory}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${empCategory}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /maintenance-emp.jsp(183,42) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("name");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                          \t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name.strCategoryName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name.strCategoryName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</option>\r\n");
          out.write("                                          ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
