/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2016-02-12 10:43:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class maintenance_002dpromdisc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./css/materialize.min.css\"  media=\"screen,projection\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/materialize.css\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/mystyle.css\"/>\r\n");
      out.write("    <!--Let browser know website is optimized for mobile-->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("    \r\n");
      out.write("      <style type=\"text/css\">\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("        .mntc {\r\n");
      out.write("            padding: 0px 0px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        .headnav, main, footer, article {\r\n");
      out.write("              padding-left: 240px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            @media only screen and (max-width : 992px) {\r\n");
      out.write("              .headnav, main, footer, article {\r\n");
      out.write("                padding-left: 0;\r\n");
      out.write("              }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        .wrapper > * {\r\n");
      out.write("          flex: 1 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .wrapper {\r\n");
      out.write("          display: -webkit-box;\r\n");
      out.write("          display: -moz-box;\r\n");
      out.write("          display: -ms-flexbox;\r\n");
      out.write("          display: -webkit-flex;\r\n");
      out.write("          display: flex;\r\n");
      out.write("          flex-direction: row;\r\n");
      out.write("        \r\n");
      out.write("          -webkit-flex-flow: row wrap;\r\n");
      out.write("          flex-flow: row wrap;\r\n");
      out.write("          -moz-flex-flow: row wrap;\r\n");
      out.write("          -o-flex-flow: row wrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("      .input-field {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("        .aside1 {\r\n");
      out.write("          background: white;\r\n");
      out.write("          border-radius: 3px;\r\n");
      out.write("          margin: 10px;\r\n");
      out.write("          text-align: center;\r\n");
      out.write("          width: 250px;\r\n");
      out.write("          height: 30%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .aside2 {\r\n");
      out.write("          background: white;\r\n");
      out.write("          border-radius: 3px;\r\n");
      out.write("          margin: 10px;\r\n");
      out.write("          text-align: center;\r\n");
      out.write("          width: 120px;\r\n");
      out.write("          height: 30%\r\n");
      out.write("        }\r\n");
      out.write("        .aside3 {\r\n");
      out.write("          background: white;\r\n");
      out.write("          border-radius: 3px;\r\n");
      out.write("          margin: 10px;\r\n");
      out.write("          text-align: center;\r\n");
      out.write("          height: 30%\r\n");
      out.write("        }\r\n");
      out.write("        .aside4 {\r\n");
      out.write("          background: white;\r\n");
      out.write("          border-radius: 3px;\r\n");
      out.write("          margin: 10px;\r\n");
      out.write("          text-align: center;\r\n");
      out.write("          height: 30%\r\n");
      out.write("        }\r\n");
      out.write("        .asidecontainer {\r\n");
      out.write("          background: transparent;\r\n");
      out.write("          margin-right: 0;\r\n");
      out.write("          text-align: center;\r\n");
      out.write("          width: 120px;\r\n");
      out.write("          height: 30%\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        @media all and (min-width: 600px) {\r\n");
      out.write("          .aside { flex: 1 auto; }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media all and (min-width: 800px) {\r\n");
      out.write("          /* We invert order of first sidebar and main\r\n");
      out.write("           * And tell the main element to take twice as much width as the other two sidebars \r\n");
      out.write("           */\r\n");
      out.write("          .main { flex: 2 0px; }\r\n");
      out.write("          \r\n");
      out.write("          .aside1 { order: 1; }\r\n");
      out.write("          .main    { order: 2; }\r\n");
      out.write("          .aside2 { order: 3; }\r\n");
      out.write("          .main    { order: 4;}\r\n");
      out.write("          .asidecontainer { order: 5;}\r\n");
      out.write("          .main    { order: 6;}\r\n");
      out.write("          .footer  { order: 7; }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body class=\"blue-grey lighten-5\">\r\n");
      out.write("  <div class=\"wrapper\">\r\n");
      out.write("        <ul id=\"slide-out\" class=\"side-nav fixed z-depth-0\">\r\n");
      out.write("          <div class=\"center\">\r\n");
      out.write("              <img src=\"./img/anon.jpg\" class=\"circle\" style=\"width: 150px; height: 150px; margin-top: 40px; margin-bottom: 20px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("          <li><a href=\"admin-home.jsp\" class=\"waves-effect waves-orange\"><b>Home</b></a>\r\n");
      out.write("          <li class=\"no-padding\">\r\n");
      out.write("            <ul class=\"collapsible collapsible-accordion\">\r\n");
      out.write("              <li>\r\n");
      out.write("                <a class=\"waves-effect waves-orange collapsible-header\"><b>Maintenance</b></a>\r\n");
      out.write("                  <div class=\"collapsible-body\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                      <li><a href=\"maintenance-emp.jsp\">Employees</a></li>\r\n");
      out.write("                      <li><a href=\"maintenance-prodsvc.jsp\">Products and Services</a></li>\r\n");
      out.write("                      <li class=\"orange\"><a href=\"#!\" class=\"waves-effect waves-orange\">Promos and Discounts</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"no-padding\">\r\n");
      out.write("            <ul class=\"collapsible collapsible-accordion\">\r\n");
      out.write("              <li>\r\n");
      out.write("                <a class=\"waves-effect waves-orange collapsible-header\"><b>Transactions</b></a>\r\n");
      out.write("                  <div class=\"collapsible-body\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                      <li><a href=\"transactions-reservation.jsp\">Reservation</a></li>\r\n");
      out.write("                      <li><a href=\"#!\">Product Order</a></li>\r\n");
      out.write("                      <li><a href=\"#!\">Walk-In</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <header class=\"headnav\">\r\n");
      out.write("               <nav class=\"z-depth-0\">\r\n");
      out.write("                 <div class=\"nav-wrapper orange\">\r\n");
      out.write("                   <a href=\"#!\" class=\"brand-logo white-text\" style=\"margin-left: 30px;\">Generic System Salon</a>\r\n");
      out.write("                 \r\n");
      out.write("                   <a href=\"#\" data-activates=\"mobile-demo\" class=\"button-collapse\"><i class=\"material-icons\">menu</i></a>\r\n");
      out.write("                   <ul class=\"side-nav\" id=\"mobile-demo\">\r\n");
      out.write("                     <li><a href=\"admin-home.jsp\" class=\"waves-effect waves-orange\"><b>Home</b></a>\r\n");
      out.write("                     <li class=\"no-padding\">\r\n");
      out.write("                       <ul class=\"collapsible collapsible-accordion\">\r\n");
      out.write("                         <li>\r\n");
      out.write("                           <a class=\"waves-effect waves-orange collapsible-header\"><b>Maintenance</b></a>\r\n");
      out.write("                             <div class=\"collapsible-body\">\r\n");
      out.write("                               <ul>\r\n");
      out.write("                                 <li><a href=\"#!\" class=\"waves-effect waves-light\">Employees</a></li>\r\n");
      out.write("                                 <li><a href=\"maintenance-prodsvc.jsp\">Products and Services</a></li>\r\n");
      out.write("                                 <li class=\"orange\"><a href=\"maintenance-servprod.jsp\">Promos and Discounts</a></li>\r\n");
      out.write("                               </ul>\r\n");
      out.write("                             </div>\r\n");
      out.write("                         </li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li class=\"no-padding\">\r\n");
      out.write("                       <ul class=\"collapsible collapsible-accordion\">\r\n");
      out.write("                         <li>\r\n");
      out.write("                           <a class=\"waves-effect waves-orange collapsible-header\"><b>Transactions</b></a>\r\n");
      out.write("                             <div class=\"collapsible-body\">\r\n");
      out.write("                               <ul>\r\n");
      out.write("                                 <li><a href=\"transactions-reservation.jsp\">Reservation</a></li>\r\n");
      out.write("                                 <li><a href=\"#!\">Product Order</a></li>\r\n");
      out.write("                                 <li><a href=\"#!\">Walk-In</a></li>\r\n");
      out.write("                               </ul>\r\n");
      out.write("                             </div>\r\n");
      out.write("                         </li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                     </li>\r\n");
      out.write("                   </ul>\r\n");
      out.write("                 </div>\r\n");
      out.write("               </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <article>\r\n");
      out.write("          <div class=\"wrapper\">\r\n");
      out.write("            \r\n");
      out.write("                    <div class=\"aside aside1 z-depth-barts\"> <!--main aside1-->\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                    <header><h4>Add Promo</h4></header>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <form class=\"col s12\">\r\n");
      out.write("                                <div class=\"input-field col s6\">\r\n");
      out.write("                                <p class=\"center\" style=\"margin-top: 23px;\">\r\n");
      out.write("                                  <input type=\"checkbox\" class=\"filled-in\" id=\"unli\"/>\r\n");
      out.write("                                  <label for=\"unli\">Unlimited</label>\r\n");
      out.write("                                </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-field col s5\">\r\n");
      out.write("                                    <span style=\"font-size: 13px; color: #9e9e9e;\">Promo Date End</span>\r\n");
      out.write("                                     <input type=\"date\" class=\"datepicker\" id=\"promoend\" placeholder=\"Date\"/>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-field col s12\">\r\n");
      out.write("                                    <input type=\"text\" class=\"validate\" id=\"promoname\">\r\n");
      out.write("                                    <label for=\"promoname\">Promo Name</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-field col s12\">\r\n");
      out.write("                                    <textarea id=\"promodetails\" class=\"materialize-textarea\" length=\"120\"></textarea>\r\n");
      out.write("                                    <label for=\"promodetails\">Promo Details</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-field col s12\">\r\n");
      out.write("                                    <select multiple id=\"promo-services-included\">\r\n");
      out.write("                                          <option value=\"\" disabled selected>Choose your option</option>\r\n");
      out.write("                                          <option value=\"1\">Service 1</option>\r\n");
      out.write("                                          <option value=\"2\">Service 2</option>\r\n");
      out.write("                                          <option value=\"3\">Service 3</option>\r\n");
      out.write("                                      </select>\r\n");
      out.write("                                      <label>Services Included</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-field col s6\">\r\n");
      out.write("                                <p class=\"center\">\r\n");
      out.write("                                    <input type=\"checkbox\" class=\"filled-in\" id=\"free\"/>\r\n");
      out.write("                                    <label for=\"free\">Free</label>\r\n");
      out.write("                                </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-field col s6\">\r\n");
      out.write("                                    <input type=\"text\" class=\"validate right-align\" id=\"promoprice\">\r\n");
      out.write("                                    <label for=\"promoprice\">Promo Price</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-field col s12 center\">\r\n");
      out.write("                                    <button class=\"waves-effect waves-light orange btn-flat\" type=\"submit\" value=\"Submit\" id=\"promobtn\">ADD</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                              </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                      <div class=\"aside aside2 z-depth-barts\">\r\n");
      out.write("                        <!-- main aside2-->\r\n");
      out.write("                        <div class=\"col s12\">\r\n");
      out.write("                            <h5>Add Discount</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                         <div class=\"row\">\r\n");
      out.write("                            <form class=\"col s12\">\r\n");
      out.write("                                <div class=\"input-field col s12\">\r\n");
      out.write("                                    <input type=\"text\" class=\"validate\" id=\"discountname\">\r\n");
      out.write("                                    <label for=\"discountname\">Discount Name</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-field col s6 offset-s5\">\r\n");
      out.write("                                    <input type=\"text\" class=\"validate right-align\" id=\"discountpercent\">\r\n");
      out.write("                                    <label for=\"discountpercent\">Discount</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col s1\">\r\n");
      out.write("                                    <h5 style=\"margin-left: -10px;\">%</h5>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col s12\" style=\"margin-top: 20px;\">\r\n");
      out.write("                                    <button class=\"waves-effect waves-light orange btn-flat\" type=\"submit\" value=\"Submit\" id=\"discountbtn\">ADD</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"aside asidecontainer z-depth-0\">\r\n");
      out.write("                      <div class=\"aside aside3 z-depth-barts\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                          <div class=\"col s12\">\r\n");
      out.write("                              <nav class=\"z-depth-0\">\r\n");
      out.write("                                <div class=\"nav-wrapper orange\" style=\"margin-top: 10px;\">\r\n");
      out.write("                                  <form>\r\n");
      out.write("                                    <div class=\"input-field z-depth-barts\">\r\n");
      out.write("                                      <input id=\"search\" type=\"search\" required>\r\n");
      out.write("                                      <label for=\"search\"><i class=\"material-icons\">search</i></label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                  </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("                              </nav>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col s12\">\r\n");
      out.write("                              <h5>Promo List</h5>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col s12\">\r\n");
      out.write("                              <ul class=\"collapsible z-depth-0\" data-collapsible=\"accordion\">\r\n");
      out.write("                                  <li>\r\n");
      out.write("                                    <div class=\"collapsible-header\"><i class=\"material-icons green-text\">info</i>Free Haircut</div>\r\n");
      out.write("                                    <div class=\"collapsible-body blue-grey lighten-5\">\r\n");
      out.write("                                      <a class=\"waves-effect waves-orange btn-flat\">Edit</a>\r\n");
      out.write("                                      <a class=\"waves-effect waves-orange btn-flat red-text\">Deactivate</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                  </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                        <div class=\"aside aside4 z-depth-barts\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                              <div class=\"col s12\">\r\n");
      out.write("                                  <nav class=\"z-depth-0\">\r\n");
      out.write("                                    <div class=\"nav-wrapper orange\" style=\"margin-top: 10px;\">\r\n");
      out.write("                                      <form>\r\n");
      out.write("                                        <div class=\"input-field z-depth-barts\">\r\n");
      out.write("                                          <input id=\"search\" type=\"search\" required>\r\n");
      out.write("                                          <label for=\"search\"><i class=\"material-icons\">search</i></label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                      </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                  </nav>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"col s12\">\r\n");
      out.write("                                  <h5>Discount List</h5>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"col s12\">\r\n");
      out.write("                                  <ul class=\"collapsible z-depth-0\" data-collapsible=\"accordion\">\r\n");
      out.write("                                      <li>\r\n");
      out.write("                                        <div class=\"collapsible-header\"><i class=\"material-icons green-text\">info</i>Senior Citizen</div>\r\n");
      out.write("                                        <div class=\"collapsible-body blue-grey lighten-5\">\r\n");
      out.write("                                          <a class=\"waves-effect waves-orange btn-flat\">Edit</a>\r\n");
      out.write("                                          <a class=\"waves-effect waves-orange btn-flat red-text\">Deactivate</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("               </div>\r\n");
      out.write("        </article>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("  <!--Import jQuery before materialize.js-->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/materialize.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        $('.datepicker').pickadate({\r\n");
      out.write("          selectMonths: true, // Creates a dropdown to control month\r\n");
      out.write("          selectYears: 15 // Creates a dropdown of 15 years to control year\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        $('select').material_select();\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
