/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2016-02-22 09:35:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class maintenance_002dprodsvc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./css/materialize.min.css\"  media=\"screen,projection\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/materialize.css\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/mystyle.css\"/>\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"./css/mtnc-productservice.css\"/>\r\n");
      out.write("    <!--Let browser know website is optimized for mobile-->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body class=\"blue-grey lighten-5\">\r\n");
      out.write("  <div class=\"wrapper\">\r\n");
      out.write("        <header class=\"headnav\">\r\n");
      out.write("                        <ul id=\"slide-out\" class=\"side-nav fixed z-depth-0\">\r\n");
      out.write("                          <div class=\"center\">\r\n");
      out.write("                              <img src=\"./img/anon.jpg\" class=\"circle\" style=\"width: 150px; height: 150px; margin-top: 40px; margin-bottom: 20px;\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                          <li><a href=\"admin-home.jsp\" class=\"waves-effect waves-orange\"><b>Home</b></a></li>\r\n");
      out.write("                         <!--  <li class=\"no-padding\"> -->\r\n");
      out.write("                            <ul class=\"collapsible\" data-collapsible=\"accordion\">\r\n");
      out.write("                              <li>\r\n");
      out.write("                                <a class=\"collapsible-header\"><b>Maintenance</b></a>\r\n");
      out.write("                                  <div class=\"collapsible-body\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                      <li><a href=\"maintenance-emp.jsp\">Employee</a></li>\r\n");
      out.write("                                      <li class=\"orange\"><a href=\"maintenance-prodsvc.jsp\">Product & Service</a></li>\r\n");
      out.write("                                      <li><a href=\"maintenance-promdisc.jsp\">Promo & Discount</a></li>\r\n");
      out.write("                                      <li><a href=\"maintenance-package.jsp\">Package</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                              </li>\r\n");
      out.write("                              <li>\r\n");
      out.write("                                <a class=\"collapsible-header\"><b>Transaction</b></a>\r\n");
      out.write("                                  <div class=\"collapsible-body\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                      <li><a href=\"transactions-reservation.jsp\">Reservation</a></li>\r\n");
      out.write("                                      <li><a href=\"transactions-productorder.jsp\">Product Order</a></li>\r\n");
      out.write("                                      <li><a href=\"#!\">Walk-In</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                              </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                          <li><a href=\"utilities.jsp\" class=\"waves-effect waves-orange\"><b>Utilities</b></a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                       <nav class=\"z-depth-0\">\r\n");
      out.write("                         <div class=\"nav-wrapper orange\">\r\n");
      out.write("                           <a href=\"#!\" class=\"brand-logo white-text\" style=\"margin-left: 30px;\">Salon Management System</a>\r\n");
      out.write("                         \r\n");
      out.write("                           <a href=\"#\" data-activates=\"mobile-demo\" class=\"button-collapse\"><i class=\"material-icons\">menu</i></a>\r\n");
      out.write("                           <ul class=\"side-nav\" id=\"mobile-demo\">\r\n");
      out.write("                             <li><a href=\"admin-home.jsp\" class=\"waves-effect waves-orange\"><b>Home</b></a>\r\n");
      out.write("                               <ul class=\"collapsible collapsible-accordion\">\r\n");
      out.write("                                 <li>\r\n");
      out.write("                                   <a class=\"waves-effect waves-orange collapsible-header\"><b>Maintenance</b></a>\r\n");
      out.write("                                     <div class=\"collapsible-body\">\r\n");
      out.write("                                       <ul>\r\n");
      out.write("                                         <li><a href=\"maintenance-emp.jsp\">Employee</a></li>\r\n");
      out.write("                                         <li class=\"orange\"><a href=\"maintenance-prodsvc.jsp\">Product & Service</a></li>\r\n");
      out.write("                                         <li><a href=\"maintenance-promdisc.jsp\">Promo & Discount</a></li>\r\n");
      out.write("                                         <li><a href=\"maintenance-package.jsp\">Package</a></li>\r\n");
      out.write("                                       </ul>\r\n");
      out.write("                                     </div>\r\n");
      out.write("                                 </li>\r\n");
      out.write("                                 <li>\r\n");
      out.write("                                   <a class=\"waves-effect waves-orange collapsible-header\"><b>Transaction</b></a>\r\n");
      out.write("                                     <div class=\"collapsible-body\">\r\n");
      out.write("                                       <ul>\r\n");
      out.write("                                         <li><a href=\"transactions-reservation.jsp\">Reservation</a></li>\r\n");
      out.write("                                         <li><a href=\"transactions-productorder.jsp\">Product Order</a></li>\r\n");
      out.write("                                         <li><a href=\"#!\">Walk-In</a></li>\r\n");
      out.write("                                       </ul>\r\n");
      out.write("                                     </div>\r\n");
      out.write("                                 </li>\r\n");
      out.write("                               </ul>\r\n");
      out.write("                             <li><a href=\"utilities.jsp\" class=\"waves-effect waves-orange\"><b>Utilities</b></a></li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                         </div>\r\n");
      out.write("                       </nav>\r\n");
      out.write("                </header>\r\n");
      out.write("\r\n");
      out.write("        <article>\r\n");
      out.write("          <div class=\"wrapper\">\r\n");
      out.write("            <!-- \r\n");
      out.write("                    <div class=\"aside aside1 z-depth-barts\"> main aside1\r\n");
      out.write("                    \r\n");
      out.write("                    </div> -->\r\n");
      out.write("                      <div class=\"aside aside1 z-depth-barts\">\r\n");
      out.write("                        <!-- main aside2-->\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                                            <header><h4>Product & Service Maintenance</h4></header>\r\n");
      out.write("                                                <div class=\"row\">\r\n");
      out.write("                                                    <form class=\"col s12\">\r\n");
      out.write("                                                        <div class=\"input-field col s4\">\r\n");
      out.write("                                                            <label class=\"red-text\">(*) Indicates required field</label>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"input-field col s12\">\r\n");
      out.write("                                                                <img  id=\"serviceimg\" style=\"width: 120px; height: 120px;\" src=\"\" alt=\"Image\"/>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"input-field col s12\" style=\"margin-top: 10px;\">\r\n");
      out.write("                                                              <select id=\"typeid\">\r\n");
      out.write("                                                                <option value=\"Product\" selected>Product</option>\r\n");
      out.write("                                                                <option value=\"Service\">Service</option>\r\n");
      out.write("                                                              </select>\r\n");
      out.write("                                                              <label for=\"typeid\">Type <span class=\"red-text\">*</span></label>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"input-field col s12\" style=\"margin-top: 30px;\">\r\n");
      out.write("                                                            <div class=\"file-field\">\r\n");
      out.write("                                                                  <div class=\"btn orange\">\r\n");
      out.write("                                                                    <span class=\"\">Image</span>\r\n");
      out.write("                                                                    <input type=\"file\" accept=\"image/*\" onchange=\"ServiceImage(this)\">\r\n");
      out.write("                                                                  </div>\r\n");
      out.write("                                                                  <div class=\"file-path-wrapper\">\r\n");
      out.write("                                                                    <input class=\"file-path validate\" type=\"text\">\r\n");
      out.write("                                                                  </div>\r\n");
      out.write("                                                              </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"input-field col s12\">\r\n");
      out.write("                                                            <input type=\"text\" class=\"validate\" id=\"servicename\">\r\n");
      out.write("                                                            <label for=\"servicename\">Name <span class=\"red-text\">*</span></label>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"input-field col s12\">\r\n");
      out.write("                                                            <textarea id=\"servicedetails\" class=\"materialize-textarea\" length=\"120\"></textarea>\r\n");
      out.write("                                                            <label for=\"servicedetails\">Details</label>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"input-field col s5\">\r\n");
      out.write("                                                            <select id=\"servicecategory\">\r\n");
      out.write("                                                                  <option value=\"\" disabled selected>Choose your option</option>\r\n");
      out.write("                                                              </select>\r\n");
      out.write("                                                              <label>Category <span class=\"red-text\">*</span></label>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"input-field col s3\" style=\"margin-top: -0.2px;\">\r\n");
      out.write("                                                            <p style=\"margin-top: 5px;\" class=\"center\"><a id=\"optionadd\" class=\"waves-effect waves-light orange-btn\"><i class=\"material-icons small\">add</i></a><a class=\"waves-effect waves-light orange-btn\" onclick=\"removeopt()\"><i class=\"material-icons small\">remove</i></a></p>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"input-field col s4\" style=\"margin-top: -4px;\">\r\n");
      out.write("                                                            <input type=\"text\" id=\"add-optname\" class=\"validate\">\r\n");
      out.write("                                                            <label for=\"add-optname\">Another</label>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"input-field col s6 offset-s6\">\r\n");
      out.write("                                                            <input type=\"text\" class=\"validate right-align\" id=\"serviceprice\" maxlength=\"8\">\r\n");
      out.write("                                                            <label for=\"serviceprice\">Price <span class=\"red-text\">*</span></label>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"input-field col s12 center\">\r\n");
      out.write("                                                            <button class=\"waves-effect waves-light orange btn-flat\" type=\"submit\" value=\"Submit\" id=\"servicebtn\" onclick=\"success()\">Create</button>\r\n");
      out.write("                                                            <button class=\"waves-effect waves-light btn-flat\" type=\"reset\" value=\"Reset\" id=\"productclear\">CLEAR</button>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                      </form>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"aside asidecontainer z-depth-0\">\r\n");
      out.write("                      <div class=\"aside aside3 z-depth-barts\">\r\n");
      out.write("                              <nav class=\"z-depth-0\">\r\n");
      out.write("                                <div class=\"nav-wrapper grey lighten-3 grey-text text-darken-4\">\r\n");
      out.write("                                  <form>\r\n");
      out.write("                                    <div class=\"input-field col s12 z-depth-0\">\r\n");
      out.write("                                      <input class=\"grey lighten-1\" id=\"search\" type=\"search\" required>\r\n");
      out.write("                                      <label for=\"search\"><i class=\"material-icons grey-text text-darken-3\">search</i></label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                  </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("                              </nav>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                          <div class=\"col s12\">\r\n");
      out.write("                              <h5>Product List</h5>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"col s12\">\r\n");
      out.write("                              <ul class=\"collapsible z-depth-0\" data-collapsible=\"accordion\">\r\n");
      out.write("                                  <li>\r\n");
      out.write("                                    <div class=\"collapsible-header\"><i class=\"material-icons green-text\">info</i>Green Hair Color</div>\r\n");
      out.write("                                    <div class=\"collapsible-body blue-grey lighten-5\">\r\n");
      out.write("                                      <a class=\"waves-effect waves-orange btn-flat\">Update</a>\r\n");
      out.write("                                      <a class=\"waves-effect waves-orange btn-flat red-text\">Deactivate</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                  </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                        <div class=\"aside aside4 z-depth-barts\">\r\n");
      out.write("                                  <nav class=\"z-depth-0\">\r\n");
      out.write("                                    <div class=\"nav-wrapper grey lighten-3 grey-text text-darken-4\">\r\n");
      out.write("                                      <form>\r\n");
      out.write("                                        <div class=\"input-field col s12 z-depth-0\">\r\n");
      out.write("                                          <input class=\"grey lighten-1\" id=\"search\" type=\"search\" required>\r\n");
      out.write("                                          <label for=\"search\"><i class=\"material-icons grey-text text-darken-3\">search</i></label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                      </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                  </nav>\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                              <div class=\"col s12\">\r\n");
      out.write("                                  <h5>Service List</h5>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"col s12\">\r\n");
      out.write("                                  <ul class=\"collapsible z-depth-0\" data-collapsible=\"accordion\">\r\n");
      out.write("                                      <li>\r\n");
      out.write("                                        <div class=\"collapsible-header\"><i class=\"material-icons green-text\">info</i>Clean Cut</div>\r\n");
      out.write("                                        <div class=\"collapsible-body blue-grey lighten-5\">\r\n");
      out.write("                                          <a class=\"waves-effect waves-orange btn-flat\">Update</a>\r\n");
      out.write("                                          <a class=\"waves-effect waves-orange btn-flat red-text\">Deactivate</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                      </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("               \r\n");
      out.write("        </article>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  <!--Import jQuery before materialize.js-->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/materialize.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("      $( document ).ready(function(){\r\n");
      out.write("        $(\".button-collapse\").sideNav();\r\n");
      out.write("          // Initialize collapsible (uncomment the line below if you use the dropdown variation)\r\n");
      out.write("        $('.collapsible').collapsible();\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        $('.datepicker').pickadate({\r\n");
      out.write("          selectMonths: true, // Creates a dropdown to control month\r\n");
      out.write("          selectYears: 15 // Creates a dropdown of 15 years to control year\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("      $(document).ready(function() {\r\n");
      out.write("          $('select').material_select();\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <!-- upload image -->\r\n");
      out.write("    <script text=\"text/javascript\">\r\n");
      out.write("      var loadFile = function(event) {\r\n");
      out.write("        var productimg = document.getElementById('productimg');\r\n");
      out.write("        productimg.src = URL.createObjectURL(event.target.files[0]);\r\n");
      out.write("      };\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    function ServiceImage(input) {\r\n");
      out.write("            if (input.files && input.files[0]) {\r\n");
      out.write("                var reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("                reader.onload = function (e) {\r\n");
      out.write("                    $('#serviceimg')\r\n");
      out.write("                        .attr('src', e.target.result)\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                reader.readAsDataURL(input.files[0]);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("   \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    function ProductImage(input) {\r\n");
      out.write("            if (input.files && input.files[0]) {\r\n");
      out.write("                var reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("                reader.onload = function (e) {\r\n");
      out.write("                    $('#productimg')\r\n");
      out.write("                        .attr('src', e.target.result)\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                reader.readAsDataURL(input.files[0]);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    function success(){\r\n");
      out.write("      alert(\"Successfully Created!\");\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
